name: "Run All Strategy Tests"

on:
  push:
    branches: [ main ]

jobs:
  separate-packages-legacy-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:2
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Composer Install
        run: cd composer-autoload-separate-packages/legacy-app && composer install
      - name: Run Test
        run: php composer-autoload-separate-packages/legacy-app/src/legacy-test.php

  separate-packages-new-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:2
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Composer Install
        run: cd composer-autoload-separate-packages/new-app/api && composer install
      - name: Run Test
        run: php composer-autoload-separate-packages/new-app/api/src/new-test.php
